# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FIRSTÂ® Alumni & Mentors Network at Michigan
email: pcbonnen@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Website for the FAMNM. Has resources for teams, students, and associated organizations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: TheFAMNM
github_username:  famnm

# Build settings
markdown: kramdown

# Plugins (Jekyll >= 3.5.0)
plugins:
    - jekyll-redirect-from
