# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FIRSTÂ® Alumni & Mentors Network at Michigan
email: pcbonnen@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  The FAMNM's website full of totally awesome shiiit
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://famnm.club" # the base hostname & protocol for your site
twitter_username: TheFAMNM
github_username:  famnm

# Build settings
markdown: kramdown
